package idleSorvererV2.enums;

public enum EnchantEffectType {
    PLAYER_PRIMARY_STAT_ADD_FLAT,
    PLAYER_SECONDARY_STAT_ADD_FLAT,
    PLAYER_SECONDARY_STAT_ADD_PERCENT,
    PLAYER_DAMAGE_TYPE_ADD_PERCENT,
    PLAYER_HEALING_TYPE_ADD_PERCENT,
    SPELL_CORE_VALUE_ADD_FLAT,
    SPELL_CORE_VALUE_ADD_PERCENT,
    SPELL_COOLDOWN_REDUCE_PERCENT,
    SPELL_ACCURACY_ADD_FLAT
}