package idleSorvererV2.enums;

public enum EnchantTargetParameter {
    // For PLAYER_PRIMARY_STAT_ADD_FLAT (matches PrimaryAttributeType names)
    AGILITY, CHARM, CUNNING, DEXTERITY, FORTITUDE, INTELLECT, MALICE, MIND, PIETY, WISDOM,

    // For PLAYER_SECONDARY_STAT_ADD_FLAT
    MAX_HP, ARMOR, HP_REGEN_PER_SEC,

    // For PLAYER_SECONDARY_STAT_ADD_PERCENT
    DODGE_CHANCE_PERCENT, GLOBAL_ACCURACY_PERCENT, GLOBAL_CAST_HASTE_PERCENT,
    SHIELD_EFFECTIVENESS_PERCENT, DEBUFF_EFFECTIVENESS_PERCENT, GLOBAL_HEALING_EFFECTIVENESS_PERCENT,

    // For PLAYER_DAMAGE_TYPE_ADD_PERCENT (matches DamageType names)
    PHYSICAL_DAMAGE, ARCANE_DAMAGE, ASTRAL_DAMAGE, SONIC_DAMAGE, ACID_DAMAGE,
    FIRE_DAMAGE, COLD_DAMAGE, DARK_DAMAGE, PSYCHIC_DAMAGE, HOLY_DAMAGE,
    LIGHTNING_DAMAGE, ENTROPY_DAMAGE, GENERAL_DAMAGE,

    // For PLAYER_HEALING_TYPE_ADD_PERCENT (matches HealingType names)
    CHARM_HEALING, PIETY_HEALING, WISDOM_HEALING, GENERAL_HEALING,

    // For SPELL_* enchants, the target is implicitly "THIS_SPELL" for its category
    THIS_SPELL_POTENCY, THIS_SPELL_COOLDOWN, THIS_SPELL_ACCURACY
}